apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsnginx
  labels:
    role: nginx
    type: deploy
    formateur: Frazer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        type: pod
        formateur: Frazer
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080